apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management-system
  labels:
    app: sms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms
  template:
    metadata:
      labels:
        app: sms
    spec:
      containers:
        - name: sms
          image: docker.io/<DOCKERHUB_USERNAME>/student-management-system:latest
          imagePullPolicy: Always
          # If your app listens on a port (not true for current CLI),
          # expose it here and in the Service, e.g.:
          # ports:
          #   - containerPort: 8080
          # If the app exits immediately, it will restart. That's expected for a CLI app.
      # If your Docker Hub repo is PRIVATE, uncomment the next lines and create the secret in step 3.
      # imagePullSecrets:
      #   - name: dockerhub-secret
