apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management-system
  labels:
    app: sms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms
  template:
    metadata:
      labels:
        app: sms
    spec:
      containers:
        - name: sms
          image: docker.io/mrunalvekariya/student-management-system:latest
          imagePullPolicy: Always
