name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Step 3: Setup Gradle (enables caching of dependencies)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Step 4: Build and run tests
      - name: Build and run tests
        run: ./gradlew clean test --info

      # Optional: Upload test results to GitHub (for better visibility)
      - name: Upload JUnit test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report
          path: build/test-results/test/

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 6: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/student-management-system:latest .

      # Step 7: Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/student-management-system:latest
