name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Step 3: Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Step 4: Build and test
      - name: Build project and run tests
        run: ./gradlew clean build

      # Step 5: Verify JAR exists (debugging aid)
      - name: List build/libs
        run: ls -l build/libs

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 7: Build Docker image (after Gradle built the JAR)
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/student-management-system:latest .

      # Step 8: Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/student-management-system:latest
